Repository Dev-Kkoddorong/ClipStory-server, pull requests merged in 2024-05, with the labels that each got.

#17 TC-23#16 : JWT와 SpringSecurity를 활용한 로그인 api 작성
  build.gradle
  src/main/java/com/clipstory/clipstoryserver/controller/AuthController.java
  src/main/java/com/clipstory/clipstoryserver/domain/Member.java
  src/main/java/com/clipstory/clipstoryserver/domain/Role.java
  src/main/java/com/clipstory/clipstoryserver/domain/Token.java
  src/main/java/com/clipstory/clipstoryserver/global/auth/AuthenticationConfig.java
  src/main/java/com/clipstory/clipstoryserver/global/auth/AuthenticationProviderImpl.java
  src/main/java/com/clipstory/clipstoryserver/global/auth/CustomAccessDeniedHandler.java
  src/main/java/com/clipstory/clipstoryserver/global/auth/CustomAuthenticationEntryPoint.java
  src/main/java/com/clipstory/clipstoryserver/global/auth/CustomUserDetailService.java
  src/main/java/com/clipstory/clipstoryserver/global/auth/JwtExceptionFilter.java
  src/main/java/com/clipstory/clipstoryserver/global/auth/JwtFilter.java
  src/main/java/com/clipstory/clipstoryserver/global/auth/JwtProvider.java
  src/main/java/com/clipstory/clipstoryserver/global/config/SecurityConfig.java
  src/main/java/com/clipstory/clipstoryserver/global/config/SwaggerConfig.java
  src/main/java/com/clipstory/clipstoryserver/global/response/Status.java
  src/main/java/com/clipstory/clipstoryserver/requestDto/LoginRequestDto.java
  src/main/java/com/clipstory/clipstoryserver/responseDto/JwtResponseDto.java
  src/main/java/com/clipstory/clipstoryserver/service/AuthService.java
  src/main/java/com/clipstory/clipstoryserver/service/InitService.java
  src/main/java/com/clipstory/clipstoryserver/service/MemberService.java
  src/main/resources/application.yml
Labels: :sparkles: feat

#20 TC-22#18 : 회원가입 api와 로그인 사용자 확인 메소드 작성
  src/main/java/com/clipstory/clipstoryserver/controller/AuthController.java
  src/main/java/com/clipstory/clipstoryserver/domain/Member.java
  src/main/java/com/clipstory/clipstoryserver/global/response/Status.java
  src/main/java/com/clipstory/clipstoryserver/repository/MemberRepository.java
  src/main/java/com/clipstory/clipstoryserver/requestDto/MemberRequestDto.java
  src/main/java/com/clipstory/clipstoryserver/service/AuthService.java
  src/main/java/com/clipstory/clipstoryserver/service/MemberService.java
Labels: :sparkles: feat

#21 TC-25#19: 코사인 유사도 최적화 #19
  src/main/java/com/clipstory/clipstoryserver/responseDto/MovieSuggestionService.java
  src/main/java/com/clipstory/clipstoryserver/service/InitService.java
  src/main/java/com/clipstory/clipstoryserver/service/MovieService.java
Labels: :hammer: fix, :recycle: refactor

#23 fix: 장르, 태그의 유사도 영향력 밸런스 패치 #22
  src/main/java/com/clipstory/clipstoryserver/responseDto/MovieSuggestionService.java
  src/main/java/com/clipstory/clipstoryserver/service/MovieService.java
Labels: :hammer: fix

#25 TC-29#24: 평가 개수가 적은 영화 추천 안함
  src/main/java/com/clipstory/clipstoryserver/controller/MovieSuggestionController.java
  src/main/java/com/clipstory/clipstoryserver/repository/RatingRepository.java
  src/main/java/com/clipstory/clipstoryserver/service/MovieService.java
  src/main/java/com/clipstory/clipstoryserver/service/MovieSuggestionService.java
  src/main/java/com/clipstory/clipstoryserver/service/RatingService.java
Labels: :sparkles: feat

#28 TC-33#27: RatingService관련 Api 및 연산 최적화
  src/main/java/com/clipstory/clipstoryserver/domain/Movie.java
  src/main/java/com/clipstory/clipstoryserver/domain/Rating.java
  src/main/java/com/clipstory/clipstoryserver/global/response/Status.java
  src/main/java/com/clipstory/clipstoryserver/responseDto/MovieResponseDto.java
  src/main/java/com/clipstory/clipstoryserver/service/InitService.java
  src/main/java/com/clipstory/clipstoryserver/service/MovieService.java
  src/main/java/com/clipstory/clipstoryserver/service/MovieSuggestionService.java
  src/main/java/com/clipstory/clipstoryserver/service/RatingService.java
Labels: :bug: bug, :sparkles: feat, :hammer: fix, :recycle: refactor

#29 TC-24#26: 외부 api 호출 로직 추가, 데이터 적재 bulk 연산 로직 개발
  src/main/java/com/clipstory/clipstoryserver/controller/InitController.java
  src/main/java/com/clipstory/clipstoryserver/domain/Movie.java
  src/main/java/com/clipstory/clipstoryserver/domain/Rating.java
  src/main/java/com/clipstory/clipstoryserver/domain/Tag.java
  src/main/java/com/clipstory/clipstoryserver/repository/BulkRepository.java
  src/main/java/com/clipstory/clipstoryserver/responseDto/MovieExtraInformationResponseDto.java
  src/main/java/com/clipstory/clipstoryserver/responseDto/MovieResponseDto.java
  src/main/java/com/clipstory/clipstoryserver/service/InitService.java
  src/main/java/com/clipstory/clipstoryserver/service/MovieService.java
  src/main/java/com/clipstory/clipstoryserver/service/MovieSuggestionService.java
  src/main/java/com/clipstory/clipstoryserver/service/RatingService.java
  src/main/java/com/clipstory/clipstoryserver/service/TagService.java
  src/main/resources/application.yml
  src/main/resources/static/movies0.csv
Labels: :sparkles: feat, :hammer: fix

#31 TC-35#30: 인증/인가 로직 수정
  src/main/java/com/clipstory/clipstoryserver/controller/MovieSuggestionController.java
  src/main/java/com/clipstory/clipstoryserver/global/config/SecurityConfig.java
  src/main/java/com/clipstory/clipstoryserver/global/response/GlobalExceptionHandler.java
Labels: :hammer: fix

#32 Sprint2종료
  build.gradle
  src/main/java/com/clipstory/clipstoryserver/controller/AuthController.java
  src/main/java/com/clipstory/clipstoryserver/controller/InitController.java
  src/main/java/com/clipstory/clipstoryserver/controller/MovieSuggestionController.java
  src/main/java/com/clipstory/clipstoryserver/domain/Member.java
  src/main/java/com/clipstory/clipstoryserver/domain/Movie.java
  src/main/java/com/clipstory/clipstoryserver/domain/Rating.java
  src/main/java/com/clipstory/clipstoryserver/domain/Role.java
  src/main/java/com/clipstory/clipstoryserver/domain/Tag.java
  src/main/java/com/clipstory/clipstoryserver/domain/Token.java
  src/main/java/com/clipstory/clipstoryserver/global/auth/AuthenticationConfig.java
  src/main/java/com/clipstory/clipstoryserver/global/auth/AuthenticationProviderImpl.java
  src/main/java/com/clipstory/clipstoryserver/global/auth/CustomAccessDeniedHandler.java
  src/main/java/com/clipstory/clipstoryserver/global/auth/CustomAuthenticationEntryPoint.java
  src/main/java/com/clipstory/clipstoryserver/global/auth/CustomUserDetailService.java
  src/main/java/com/clipstory/clipstoryserver/global/auth/JwtExceptionFilter.java
  src/main/java/com/clipstory/clipstoryserver/global/auth/JwtFilter.java
  src/main/java/com/clipstory/clipstoryserver/global/auth/JwtProvider.java
  src/main/java/com/clipstory/clipstoryserver/global/config/SecurityConfig.java
  src/main/java/com/clipstory/clipstoryserver/global/config/SwaggerConfig.java
  src/main/java/com/clipstory/clipstoryserver/global/response/GlobalExceptionHandler.java
  src/main/java/com/clipstory/clipstoryserver/global/response/Status.java
  src/main/java/com/clipstory/clipstoryserver/repository/BulkRepository.java
  src/main/java/com/clipstory/clipstoryserver/repository/MemberRepository.java
  src/main/java/com/clipstory/clipstoryserver/repository/RatingRepository.java
  src/main/java/com/clipstory/clipstoryserver/requestDto/LoginRequestDto.java
  src/main/java/com/clipstory/clipstoryserver/requestDto/MemberRequestDto.java
  src/main/java/com/clipstory/clipstoryserver/responseDto/JwtResponseDto.java
  src/main/java/com/clipstory/clipstoryserver/responseDto/MovieExtraInformationResponseDto.java
  src/main/java/com/clipstory/clipstoryserver/responseDto/MovieResponseDto.java
  src/main/java/com/clipstory/clipstoryserver/service/AuthService.java
  src/main/java/com/clipstory/clipstoryserver/service/InitService.java
  src/main/java/com/clipstory/clipstoryserver/service/MemberService.java
  src/main/java/com/clipstory/clipstoryserver/service/MovieService.java
  src/main/java/com/clipstory/clipstoryserver/service/MovieSuggestionService.java
  src/main/java/com/clipstory/clipstoryserver/service/RatingService.java
  src/main/java/com/clipstory/clipstoryserver/service/TagService.java
  src/main/resources/application.yml
  src/main/resources/static/movies0.csv
Labels: :safety_vest: setting

#34 TC-27#33: K-nn 알고리즘 적용
  src/main/java/com/clipstory/clipstoryserver/controller/MovieSuggestionController.java
  src/main/java/com/clipstory/clipstoryserver/domain/Member.java
  src/main/java/com/clipstory/clipstoryserver/domain/Movie.java
  src/main/java/com/clipstory/clipstoryserver/domain/Rating.java
  src/main/java/com/clipstory/clipstoryserver/domain/Tag.java
  src/main/java/com/clipstory/clipstoryserver/service/GenreService.java
  src/main/java/com/clipstory/clipstoryserver/service/InitService.java
  src/main/java/com/clipstory/clipstoryserver/service/MemberService.java
  src/main/java/com/clipstory/clipstoryserver/service/MovieSuggestionService.java
Labels: :sparkles: feat

#36 TC-45#35: 장르별로 영화 조회 api 작성
  src/main/java/com/clipstory/clipstoryserver/controller/MovieController.java
  src/main/java/com/clipstory/clipstoryserver/repository/MovieRepository.java
  src/main/java/com/clipstory/clipstoryserver/service/MovieService.java
Labels: :sparkles: feat

#38 TC-46#37: K-nn, 코사인유사도 최적화
  src/main/java/com/clipstory/clipstoryserver/domain/Member.java
  src/main/java/com/clipstory/clipstoryserver/responseDto/MovieResponseDto.java
  src/main/java/com/clipstory/clipstoryserver/service/MemberService.java
  src/main/java/com/clipstory/clipstoryserver/service/MovieSuggestionService.java
Labels: :hammer: fix

#40 TC-47#39 TMDB API 호출 최적화
  src/main/java/com/clipstory/clipstoryserver/domain/Movie.java
  src/main/java/com/clipstory/clipstoryserver/responseDto/MovieResponseDto.java
  src/main/java/com/clipstory/clipstoryserver/responseDto/PagedResponseDto.java
  src/main/java/com/clipstory/clipstoryserver/service/MemberService.java
  src/main/java/com/clipstory/clipstoryserver/service/MovieService.java
  src/main/java/com/clipstory/clipstoryserver/service/MovieSuggestionService.java
Labels: :hammer: fix
